### ISSUE TITLE
Starlark mailing list is private or missing (part deux)

### ISSUE THREAD

**Issue by joeflack4** [bazelbuild/starlark#86] opened 2019-10-29 23:54 UTC
This is a duplicate of: #74 

I'm only creating a new issue because the old issue is closed but people are still reporting this problem.

Here's what people see when they try to click the link:
```
This group either doesn't exist, or you don't have permission to access it. If you're sure this group exists, contact the Owner of the group and ask them to give you access.
```
<img width="567" alt="Screen Shot 2019-10-29 at 7 51 47 PM" src="https://user-images.githubusercontent.com/13045020/67817939-da34d280-fa85-11e9-8731-653f6d4830a2.png">

**Comment by joeflack4** [comment] 2019-10-29 23:54
Also, I was wondering why the language doesn't support recursion. I'm not sure it is possible to be a full-blown Turing complete general purpose programming language without it. This is why I was going to join / post to the mailing list.

**Comment by jmillikin-stripe** [comment] 2019-10-30 00:05
> Also, I was wondering why the language doesn't support recursion. I'm not sure it is possible to be a full-blown Turing complete general purpose programming language without it.

Starlark is, by design, not Turing-complete. It's intended to be a fully sandboxed configuration syntax that plugs in to larger tools.

**Comment by joeflack4** [comment] 2019-10-30 00:09
I see! Thanks for the clarification.

**Comment by laurentlb** [comment] 2020-01-28 21:51
I've updated the group settings (I don't know why it magically changed a few months ago). Can you confirm it's working?

(in any case, you didn't miss much, there has been little activity there)

**Comment by joeflack4** [comment] 2020-01-28 21:54
It's working! I can see everything now!

**Comment by jmillikin-stripe** [comment] 2020-01-28 22:25
I confirm it works for me too. Thanks for following up!

**Comment by alandonovan** [comment] 2020-07-22 18:37
@laurent You can close this now. (Apparently I don't have the power to do that in this repo.)

**Closed** 2020-07-23 00:08 UTC
