### ISSUE TITLE
f-strings in Bazel?

### ISSUE THREAD

**Issue by daniel-v-klein** [bazelbuild/starlark#205] opened 2021-08-20 16:31 UTC
Since Bazel is so Pythonesque, it'd be great if it supported the PY3 notion of f-strings https://docs.python.org/3/tutorial/inputoutput.html#fancier-output-formatting

**Comment by mahmoudimus** [comment] 2021-08-20 17:34
dupe of https://github.com/bazelbuild/starlark/issues/91

**Comment by albertocavalcante** [comment] 2024-07-29 17:28
@ndmitchell @laurentlb Do you have entitlement to close issues? Not sure how closing of duplicates is handled on this repo.

**Comment by ndmitchell** [comment] 2024-07-30 12:24
I never had issue close permissions.

**Closed** 2024-12-19 20:54 UTC
